### ISSUE TITLE
Organize cheats in folders

### ISSUE THREAD

**Issue by Blackvz** [wx-Yao/alfred-cheat#4]
There shoud be a way to organize cheats in folder. 

Nothing should really change in the usage of the plugin but it should search for cheats recursively.

**Comment by wx-Yao** [comment]
Cool thanks for the feedback. It's doable if you're happy with simply recursive searching. i.e., `cheat/somedir/brew.txt` is equivalent to `cheat/brew.txt`. But if you wanna do something with or reflect `somedir` itself in the calling, then it's something worth considering because I haven't thought of good ways to do that. Any suggestion or you're happy with the simplest solution?

**Comment by Blackvz** [comment]
Yep the simplest solution is enough for my purpose.

**Comment by wx-Yao** [comment]
The feature has been added. Now the tool will try to flatten every cheatsheet in the base directory. That means the directory structure is only for your management purpose. And make sure you don't have duplicated cheatsheets in different dirs (e.g, `cheat/a/ls` and `cheat/b/ls`). Otherwise, only one of them will be shown.

**Comment by wx-Yao** [comment]
Thanks for the report. And closing the issue because it's been resolved.
