### ISSUE TITLE
Placeholders in commands

### ISSUE THREAD

**Issue by mafredri** [wx-Yao/alfred-cheat#9]
Hi, first off, this is really neat. I love the idea and thanks for creating this!

I had an idea for a feature, which is to add a placeholder syntax. Let's say I write the following cheat:

```
# Format as FAT32 with 64 kB clusters
newfs_msdos -F 32 -c 128 -v NAME /dev/rdisk4s1
```

This command contains parts where we could utilize placeholders:

```
newfs_msdos -F 32 -c 128 -v [[NAME]] /dev/r[[DISK]]
```

My idea is that when the user selects this entry (containing placeholders for NAME and DISK), Alfred would prompt for their values before it's pasted/copied to clipboard.

This feature could also help protect against using dangerous hard-coded values (like disk path) which, in this case, could wipe the wrong drive.

PS. I had an idea about using globs as well [[/dev/rdisk*]] which could present a multiple-selection of available values but this only works locally and will quickly become way too complex 😄.

**Comment by wx-Yao** [comment]
Hi mafredri :)

> Hi, first off, this is really neat. I love the idea and thanks for creating this!

Thanks for using :)

> My idea is that when the user selects this entry (containing placeholders for NAME and DISK), Alfred would prompt for their values before it's pasted/copied to clipboard.

could u clarify how exactly we can populate the placeholder? i mean is there any user friendly way already in ur mind? because i can think of some ways but those are too cumbersome, i'd rather copy&paste and then move cursor to change parameters.

> This feature could also help protect against using dangerous hard-coded values (like disk path) which, in this case, could wipe the wrong drive.

Good point! Maybe I can try to replace sensitive parameters specified by special syntax (e.g. [[DISKPATH]]) with other prompt info (e.g. \<REPLACE ME\>) when pasting. I'll think about it.

> PS. I had an idea about using globs as well [[/dev/rdisk*]] which could present a multiple-selection of available values but this only works locally and will quickly become way too complex smile.

Yeah ur right. Interpretating '*' is the job the of shells. The original design of this tool doesn't include handling those syntax, and the placeholder feature which you requested. Let's not make simple stuff complicated. 

I did find a useful point in your request and i'll try to figure out a good way to implement it. But other than that, im not sure if i can add more unless u come up with a way better than simply moving cursor:) Thanks.

**Comment by wx-Yao** [comment]
Close the issue because it's inactive.
